---
 - hosts: "{{ passed_in_hosts }}"
   become: yes
   remote_user: ec2-user
   become_user: root
   tasks:
     - name: install jq, Json parser
       yum:
         name: jq
         state: present
